### PR TITLE
fix: use container to fix expansion of tab

### LINKED ISSUE #95: UI : Container length of TabStatefulScaffold in "Cupertino style" changes when switching tabs
For example, in the Github `Notificiations_Screen`, the word "Participating" is long. When the tab is `selected`, it expands the entire Tab widget. This is mostly likely because the `selected` state has a heavier `fontweight`, thus expanding the entire parent Container Widget. This occurs in Cupertino style only.

gittouch UI tab issue

Possible fix: When tab is active, do not change the `fontweight`. 
I only started learning coding and Flutter a few months ago, so if I figure it out I'll submit a merge.

### PR DESCRIPTION
**Pull request by shreyas1599**
Fixes #95 

I initially made the suggestion to change the padding to 12 from 10, but that didn't work when I tried it on the iPad. Changing to a container with a fixed width did the trick.

### CODE REVIEW

File: lib/scaffolds/tab.dart [hunk 1]
```diff
@@ -34,9 +34,11 @@ class TabScaffold extends StatelessWidget {
...
                 key,
-                Padding(
-                  padding: const EdgeInsets.symmetric(horizontal: 8),
-                  child: Text(text),
+                Container(
+                  width: 100,
+                  child: Center(
+                    child: Text(text),
+                  ),
                 ))),
```
Comment (pd4d10) [inline lib/scaffolds/tab.dart:42]: How about adding `Row > Expanded` as `CupertinoSlidingSegmentedControl`'s parent? Then it would expand to the full width.

Comment (pd4d10) [reply lib/scaffolds/tab.dart:42]: The magic number 100 would break again if the word becomes long enough at next time.

Comment (shreyas1599) [reply lib/scaffolds/tab.dart:42]: I tried using `Row > Expanded` as I mentioned in the issue. Didn't work

Comment (pd4d10) [reply lib/scaffolds/tab.dart:42]: I'm not sure if I made it clear. The following code seems work fine.

```dart

  Widget _buildTitle(BuildContext context) {
    switch (Provider.of<ThemeModel>(context).theme) {
      case AppThemeType.cupertino:
        return DefaultTextStyle(
          style: DefaultTextStyle.of(context).style.copyWith(fontSize: 14),
          child: Row(
            children: [
              Expanded(
                child: CupertinoSlidingSegmentedControl(
                  groupValue: activeTab,
                  onValueChanged: onTabSwitch,
                  children: tabs.asMap().map((key, text) => MapEntry(
                      key,
                      Padding(
                        padding: const EdgeInsets.symmetric(horizontal: 8),
                        child: Text(text),
                      ))),
                ),
              ),
            ],
          ),
        );
      default:
        return title;
    }
  }
```

image

**Comment by pd4d10** [comment]
Hi, @shreyas1599 , I've pushed an extra commit to make it ready to merge. Feel free to ping me if there are other problems.

**Comment by shreyas1599** [comment]
Hi, @pd4d10 sorry for the late reply. I understood my mistake. My mistake was that I put `Row > Expanded` under `CupertinoSlidingSegmentedControl`.
