### PR TITLE
fix: error using same token 

### LINKED ISSUE #82: Error using already used personal token on gitlab
I didn't realise that you cannot use the same token for the same app on different devices for gitlab. When a wrong token is used, as expected a 404 error is returned. But when you use an already used token the following error occurs. The only way to resolve this is to uninstall and re-install the app. Probably a gitlab bug but we should handle the error better and allow the user to enter a different token.

image

### PR DESCRIPTION
**Pull request by shreyas1599**
Fixes #82

### CODE REVIEW

File: lib/models/auth.dart [hunk 1]
```diff
@@ -148,8 +148,10 @@ class AuthModel with ChangeNotifier {
       if (info['message'] != null) {
         throw info['message'];
       }
+      if (info['username'] == null) {
+        throw "username returned is null. Make sure token is not being re-used";
+      }
```
Comment (pd4d10) [inline lib/models/auth.dart:153]: What is the response in this case? The `info` variable

Comment (pd4d10) [reply lib/models/auth.dart:153]: According to the GitLab documentation, seems all errors would be represented in the `message` field.

Comment (shreyas1599) [reply lib/models/auth.dart:153]: `message` field is null. So are all other fields of `GitlabUser`. I verified it once again.

Comment (pd4d10) [reply lib/models/auth.dart:153]: So does it mean the response json is empty, like `{}`?

Comment (shreyas1599) [reply lib/models/auth.dart:153]: Sorry should've checked the response instead of the variable after serialising it. Here's the response: 

`{error: invalid_token, error_description: Token is expired. You can either do re-authorization or token refresh.}`

I could've just used the `error` field. Might cover some other cases as well.

Comment (pd4d10) [reply lib/models/auth.dart:157]: OK. I guess it is caused by legacy version of GitLab...
